#Powerful quotes & sayings about life

quotes_teletips = [
"Love For All, Hatred For None. @GBxlimited", 
"Change the world by being yourself. @GBxlimited",
"Every moment is a fresh beginning. @GBxlimited",
"Never regret anything that made you smile. @GBxlimited",
"Die with memories, not dreams. @GBxlimited",
"Aspire to inspire before we expire. @GBxlimited",
"Everything you can imagine is real. @GBxlimited",
"Simplicity is the ultimate sophistication. @GBxlimited",
"Whatever you do, do it well. @GBxlimited",
"What we think, we become. @GBxlimited",
"All limitations are self-imposed. @GBxlimited",
"Tough times never last but tough people do. @GBxlimited",
"Problems are not stop signs, they are guidelines. @GBxlimited",
"Have enough courage to start and enough heart to finish.",
"I could agree with you but then we’d both be wrong.",
"Oh, the things you can find, if you don’t stay behind.",
"Determine your priorities and focus on them.",
"Be so good they can’t ignore you.",
"Yesterday you said tomorrow. Just do it.",
"I don’t need it to be easy, I need it to be worth it.",
"Never let your emotions overpower your intelligence.",
"Nothing lasts forever but at least we got these memories.",
"Don’t you know your imperfections is a blessing?",
"Reality is wrong, dreams are for real.",
"To live will be an awfully big adventure.",
"Try to be a rainbow in someone’s cloud.",
"There is no substitute for hard work.",
"What consumes your mind controls your life.",
"Strive for greatness. @GBxlimited",
"And still, I rise. @GBxlimited",
"The time is always right to do what is right.",
"Let the beauty of what you love be what you do.",
"May your choices reflect your hopes, not your fears.",
"A happy soul is the best shield for a cruel world.",
"White is not always light and black is not always dark.",
"Happiness depends upon ourselves. @GBxlimited",
"Turn your wounds into wisdom. @GBxlimited",
"Change the game, don’t let the game change you.",
"It hurt because it mattered. @GBxlimited",
"I will remember and recover, not forgive and forget.",
"The meaning of life is to give life meaning.",
"When words fail, music speaks.",
"Embrace the glorious mess that you are.",
"I have nothing to lose but something to gain."
]
